version: "3.9"

services:
  app:
    build: .
    container_name: php_auth_app
    ports:
      - "8000:80"
    environment:
      DB_HOST: db
      DB_NAME: php_auth
      DB_USER: root
      DB_PASS: example
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: php_auth_db
    restart: always
    environment:
      MYSQL_DATABASE: php_auth
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
